Menerjemahkan faq/windows.po
python/python-docs-id pull request #17
Opened 2021-01-01 13:46 UTC by sodrooome

Menerjemahkan kesuluruhan dokumentasi yang ada di `faq/windows.po`

2021-01-01 16:44 UTC, oonid commented
halo @sodrooome terima kasih sudah menerjemahkan dokumentasi Python melalui GitHub.
bagian yang agak panjang dari mekanisme penerjemahan di GitHub adalah harus disinkronisasi dahulu dari Transifex.
aku coba sinkronisasi sekarang, lalu nanti dicek lagi ya, semoga tidak ada yang konflik dengan penerjemahan ini.
satu hal lagi, boleh minta tolong untuk pilih "Reviewers" di menu GitHub, aku lagi mengecek perbedaan kalo aku biasanya pilih pengulas sendiri.

2021-01-01 17:36 UTC, sodrooome commented
untuk request reviewers sendiri saya tidak bisa menggunakan nya, mungkin itu hanya terbatas untuk maintainer atau kolaborator saja? @oonid

2021-01-02 01:36 UTC, oonid commented
halo @sodrooome ini branch 3.9 sudah aku perbarui, sepertinya tidak ada konflik. silakan dicoba cek juga, perbarui branch 3.9 di reponya.
silakan konfirmasi lagi nanti setelah cek tidak ada konflik.

untuk kirim kembali ke Transifex, bisa dari sisi aku tapi nanti nama kontribusi di Transifex nya berubah jadi namaku. pilihan lainnya, install aplikasi tx, lalu push sendiri ke Transifex. silakan konfirmasi juga soal pembaruan ke Transifex.

oke terima kasih soal info reviewers, sebelumnya ada PR dari eksternal juga, tapi belum tau caranya.

2021-01-02 05:06 UTC, oonid commented on faq/windows.po
> +msgstr "Bagaimana cara menjalankan program Python di Windows?"
"Bagaimana cara mengoperasikan program Python di Windows?"

hal ini mencegah kebingungan antara arti "run" menjadi "jalan".

2021-01-02 05:08 UTC, oonid commented on faq/windows.po
> +"program Anda. Jadi, bagaimana Anda mengatur penerjemah untuk menangani Python"
kalo di satu bagian sudah disebutkan sebagai *interpreter* di bagian lagi nggak perlu diubah jadi "penerjemah", agar konsisten.

2021-01-02 05:11 UTC, oonid commented on faq/windows.po
> +" aktivitas, adalah pelaku tertentu."
"all file system read activity" menjadi "semua aktivitas baca dari sistem file"

2021-01-02 05:13 UTC, oonid commented on faq/windows.po
> +"Borland note: convert :file:`python{NN}.lib` ke format OMF menggunakan "
note menjadi catatan.
convert menjadi ubah.

2021-01-02 05:14 UTC, oonid commented on faq/windows.po
> +"leo, fungsi init akan dipanggil initleo (). Jika Anda menggunakan bayangan SWIG "
dipastikan lagi kurung dari pemanggilan fungsi menempel dengan nama fungsinya.

2021-01-02 05:14 UTC, oonid commented on faq/windows.po
> +"kelas, sebagaimana seharusnya, fungsi init akan dipanggil initleoc (). Ini "
dipastikan lagi kurung dari pemanggilan fungsi menempel dengan nama fungsinya.

2021-01-02 05:16 UTC, oonid commented on faq/windows.po
>  "Alas, Py_None is a macro that expands to a reference to a complex data "
Alas di situ bisa jadi "sayangnya".

2021-01-02 05:17 UTC, oonid commented on faq/windows.po
> +"Alas, Py_None adalah makro yang meluas ke referensi ke data kompleks "
Alas di situ bisa diartikan sebagai "sayangnya".

2021-01-02 05:24 UTC, oonid requested changes
halo @sodrooome aku memberikan beberapa masukan terkait penerjemahan ya. mohon diperbarui. terima kasih.

2021-01-02 05:24 UTC, oonid commented on faq/windows.po
> +"Dimungkinkan untuk menggunakan perintah ``% typemap '' SWIG untuk membuat perubahan "
dipastikan lagi untuk semua yang dituliskan dalam petik terbalik sesuai aslinya: ``%typemap``

2021-01-02 05:24 UTC, oonid commented on faq/windows.po
> +"ke dalam Python! (Ini adalah fakta terdokumentasi kunci kedua.)"
undocumented itu tak terdokumentasi.
(Ini adalah fakta kunci tak terdokumentasi kedua.)

2021-01-02 06:17 UTC, sodrooome commented on faq/windows.po
> +"ke dalam Python! (Ini adalah fakta terdokumentasi kunci kedua.)"
Keseluruhan dokumentasi sudah saya betulkan (termasuk istilah asing atau tanda yg salah di istilah asing) di a982030.

2021-01-02 08:09 UTC, oonid approved these changes

2021-01-02 08:10 UTC, oonid commented
terima kasih @sodrooome sudah diperbaiki penerjemahannya.
satu hal lagi nih ditunggu informasinya,

untuk kirim kembali ke Transifex, bisa dari sisi aku tapi nanti nama kontribusi di Transifex nya berubah jadi namaku. pilihan lainnya, install aplikasi tx, lalu push sendiri ke Transifex. silakan konfirmasi juga soal pembaruan ke Transifex.

2021-01-02 11:35 UTC, sodrooome commented
untuk merge ke transifex melalui PR ini aja mas, ga masalah @oonid

2021-01-02 11:43 UTC, oonid commented
oke @sodrooome , nanti aku yang push kembali ke Transifex.
untuk PR yang ini akan aku "squash and merge" ke branch 3.9 dulu.
nanti pembaruan tahap berikutnya baru masuk ke master.

2021-01-02 11:45 UTC, merged

2021-01-02 11:46 UTC, oonid commented
sudah beres ya @sodrooome terima kasih atas kontribusinya.